### ISSUE TITLE
se busca: therisia

### ISSUE THREAD

**Issue by kalberto001** [LegionLatino/LegionLatinoBugs#1]
[//]: #  (Solor reportes especificos de problemas, cosas com "OMG NADA FUNCIONA, TODO ESTA BUG" Seran borrados e ignorados)

[//]: # (Por favor usa el siguiente formatot:)
[//]: # ([Mision][Nombre de la Zona] Nombre de la Mision y link de wowhead.)
https://es.wowhead.com/quest=43632/se-busca-theryssia
[//]: # ([Spell][Clase] Nombre del spell)

[//]: # ([Talento][Clase] Nombre del talento)

[//]: # ([NPCs] Nombre del NPC)
theryssia
**Nombre del PJ**:
olaf
**Descripcion**: Describe el problema
se la llama a travez de la lapida y aparece pero no deja atacarla en ningun instante
**Como funciona ahora**: Como funciona ahora en el servidor

**Como deberia funcionar**: Como de verdad deberia funcionar
![wowscrnshot_092818_161629](https://user-images.githubusercontent.com/43686525/46234173-0d64d980-c33b-11e8-8081-00e538b448aa.jpg)

**Pasos para recrear el problema**:

1. 
2. 
3.

**Comment by LegionLatino** [comment]
Fue arreglado, gracias por el reporte
