### ISSUE TITLE
falta npc

### ISSUE THREAD

**Issue by dlu389** [LegionLatino/LegionLatinoBugs#14]
[//]: # ([missing demon][Azsuna] missing demon y https://www.wowhead.com/quest=42238/missing-demon)

[//]: # ([NPCs] Daglop)

**Descripcion**: falta el demonio daglop
**Como funciona ahora**:falta el demonio daglop en la ubicacion

**Como deberia funcionar**: esta el demonio daglop rondando en un punto minimo

**Pasos para recrear el problema**: 

1. aparecer el demonio daglop y hablar con el
2. libera cadena de misiones
3.

**Comment by LegionLatino** [comment]
Gracias sera agregado el proximo restart
