### ISSUE TITLE
Bug mision Study hall combat research Azsuna

### ISSUE THREAD

**Issue by alexrepositorio** [LegionLatino/LegionLatinoBugs#18]
[//]: #  (Solor reportes especificos de problemas, cosas com "OMG NADA FUNCIONA, TODO ESTA BUG" Seran borrados e ignorados)

[//]: # (Por favor usa el siguiente formatot:)
[//]: # ([Mision][Nombre de la Zona] Nombre de la Mision y link de wowhead.)
[//]: # ([Spell][Clase] Nombre del spell)
[//]: # ([Talento][Clase] Nombre del talento)
[//]: # ([NPCs] Nombre del NPC)

**Nombre del PJ**:Axelfreed

**Descripcion**: Al momento de realizar la misión https://www.wowhead.com/quest=42371/study-hall-combat-research pide recoger el item https://www.wowhead.com/item=137426/draconic-compendium-volume-iii#objective-of sin embargo al recoger el item no se registra para avanzar en la quest.

**Como funciona ahora**: Aunque se recoja el item no crece el contador y no se puede terminar la quest

**Como deberia funcionar**: Al recoger el item el contador en la misión debe incrementar y permitir avanzar con la quest.

**Pasos para recrear el problema**:

1. Ir a Azsuna y tomar la misión https://www.wowhead.com/quest=42371/study-hall-combat-research
2. Recoger el item https://www.wowhead.com/item=137426/draconic-compendium-volume-iii

**Comment by LegionLatino** [comment]
es duplicado de #10
