### ISSUE TITLE
al morir en islas quebradas aparezco en los cementerios de los baldios

### ISSUE THREAD

**Issue by kalberto001** [LegionLatino/LegionLatinoBugs#2]
[//]: #  (Solor reportes especificos de problemas, cosas com "OMG NADA FUNCIONA, TODO ESTA BUG" Seran borrados e ignorados)

[//]: # (Por favor usa el siguiente formatot:)
[//]: # ([Mision][Nombre de la Zona] Nombre de la Mision y link de wowhead.)
[//]: # ([Spell][Clase] Nombre del spell)
[//]: # ([Talento][Clase] Nombre del talento)
[//]: # ([NPCs] Nombre del NPC)

**Nombre del PJ**:
olaf
**Descripcion**: Describe el problema
al momento de morir en cualquier localidad de islas abruptas me teletransportan a los cementerios de los baldios
**Como funciona ahora**: Como funciona ahora en el servidor

**Como deberia funcionar**: Como de verdad deberia funcionar

**Pasos para recrear el problema**:

1. 
2. 
3.
![wowscrnshot_092818_162818](https://user-images.githubusercontent.com/43686525/46234342-a1cf3c00-c33b-11e8-9f03-5d9b6589f594.jpg)

**Comment by LegionLatino** [comment]
Fue arreglado gracias por el reporte
