### ISSUE TITLE
Bug en Lista de Amigos

### ISSUE THREAD

**Issue by JavierPozzo** [LegionLatino/LegionLatinoBugs#20]
[//]: #  (Hola es para reportar un bug en la lista de amigos al momento de agregar a alguien)

**Nombre del PJ**: Ilidarier

**Descripcion**: El problema es que cuando quieres agregar a una persona a tu lista de amigos pones su nombre pero no se agrega ni pasa nada

**Como funciona ahora**: Al poner el nombre del jugador y darle añadir no se agrega

**Como deberia funcionar**: Deberia añadir a la persona a la lista de amigos

**Pasos para recrear el problema**:

1. Abrir la lista de amigos y darle en añadir amigo
2. Colocar el nombre del jugador que deseas agregar
3.Darle añadir y ver que no se añade ni hace nada

**Comment by LegionLatino** [comment]
Arreglado, por favor intenta otra vez.
