### ISSUE TITLE
Mision bug de la cadena de los Cazadores de demonios

### ISSUE THREAD

**Issue by JavierPozzo** [LegionLatino/LegionLatinoBugs#4]
Mision: [On Felbat Wings] Zona:[Garrida Ilidari-Mordum, El avismo Devastado] Link de la misino en [En las alas de un murcielago vil](https://es.wowhead.com/quest=39663/en-las-alas-de-un-murci%C3%A9lago-vil)

**Nombre del PJ**: Ilidarier

**Descripcion**: La mision consiste en que se debe tomar un murcielago infernal hacia el martillo de la luz para luchar con la reina y obtener la llave Sargerita haciendo imposible poder continuar la cadena de esta clase

**Como funciona ahora**: Al momento de hablar con la cuidadora de murcielagos lleva a todos los demas NPC pero no lleva al jugador al  martillo de la luz

**Como deberia funcionar**: Al hablar con la cuidadora de murcielagos te deberia llevar al martillo de la luz

**Pasos para recrear el problema**:

1. tomar la mision 
2. ver como todos los NPC se van volando hacia el martillo
3.hablar con la cuidadora de murcielagos y ver que no aparece ninguna opcion para ir volando
![wowscrnshot_092918_115326](https://user-images.githubusercontent.com/43704541/46247853-6128fe80-c3df-11e8-92d7-7c0fce7d18d2.jpg)

**Comment by LegionLatino** [comment]
Fue arreglada, gracias por el reporte
