### ISSUE TITLE
bug de mision de campaña 

### ISSUE THREAD

**Issue by dlu389** [LegionLatino/LegionLatinoBugs#6]
[//]: #  mision campaña demon hunter bug

[//]: # ([on felbat wings][mardum, abismo devastado] en las alas de un murcielago vil y https://es.wowhead.com/quest=39663/en-las-alas-de-un-murci%C3%A9lago-vil)

[//]: # ([NPCs] izal lunablanca)

**Kidd**:

**Descripcion**: la mision consiste en tomar el murcielago y volar asta el martillo vil, cuando intentas pedir el murcielago, el npc solo habla y no da la opcion de montar

**Como funciona ahora**: cuando intentas pedir el murcielago el npc solo habla y no da la opcion de montar

**Como deberia funcionar**: tendria q aparecer la opcion de tomar el murcielago

**Pasos para recrear el problema**:

1. hablas con el npc
2. abre el cartel de interaccion 
3.el npc responde no da opciones

**Comment by LegionLatino** [comment]
Hola, gracias por el reporte. este reporte esta duplicado (alguien ya lo reporto)
y estamos en ello 
#4 

Por favor pide ayuda de un MJ en el canal de asistencia en el discord para que un MJ te ayude manualmente
