### ISSUE TITLE
Bug misión Saving Stellagosa en Azsuna

### ISSUE THREAD

**Issue by alexrepositorio** [LegionLatino/LegionLatinoBugs#7]
[//]: #  (Solor reportes especificos de problemas, cosas com "OMG NADA FUNCIONA, TODO ESTA BUG" Seran borrados e ignorados)

[//]: # (Por favor usa el siguiente formatot:)
[//]: # ([Mision][Nombre de la Zona] Nombre de la Mision y link de wowhead.)
[//]: # ([Spell][Clase] Nombre del spell)
[//]: # ([Talento][Clase] Nombre del talento)
[//]: # ([NPCs] Nombre del NPC)

**Nombre del PJ**:Axelfreed

**Descripcion**: En la misión solicita liberar a stellagosa pero al liberar sus cadenas el contador no avanza y la misión no progresa.

**Como funciona ahora**: Aun sigue igual al liberar las cadenas no aumenta el contador y no se puede progresar en la misión.

**Como deberia funcionar**: Al liberar cada cadena se debe aumentar el contador de la misión para avanzar en la misma y entregarla.

**Pasos para recrear el problema**:

1. Obtener la misión saving Stellagosa Wowhead:https://www.wowhead.com/quest=37450/saving-stellagosa
2. Matar a Overseer Lykill
3.Intentar liberar las cadenas de Stellagosa

**Comment by LegionLatino** [comment]
Gracias, se arreglo y sera aplicado en el proximo restarte del servidor

**Comment by alexrepositorio** [comment]
El bug continua acabo de tratar de hacer la misión con una cazadora de demonios pero aun no se puede.
