### ISSUE TITLE
Bug The death of the eldest azsuna

### ISSUE THREAD

**Issue by alexrepositorio** [LegionLatino/LegionLatinoBugs#9]
[//]: #  (Solor reportes especificos de problemas, cosas com "OMG NADA FUNCIONA, TODO ESTA BUG" Seran borrados e ignorados)

[//]: # (Por favor usa el siguiente formatot:)
[//]: # ([Mision][Nombre de la Zona] Nombre de la Mision y link de wowhead.)
[//]: # ([Spell][Clase] Nombre del spell)
[//]: # ([Talento][Clase] Nombre del talento)
[//]: # ([NPCs] Nombre del NPC)

**Nombre del PJ**:Axelfreed

**Descripcion**: En la misión hay que obtener el item https://www.wowhead.com/item=122095/crackling-leyworm-core de los burrowing leyworms sin embargo al matarlos nunca dropean dicho item.

**Como funciona ahora**: Nunca dropean el item.

**Como deberia funcionar**: Deberían dropear el item.

**Pasos para recrear el problema**:

1. Coger la misión https://www.wowhead.com/quest=37853/the-death-of-the-eldest en Azsuna
2. Matar burrowing leyworm

**Comment by LegionLatino** [comment]
Hola, el item si dropea pero el drop rate es bajo, se aumentara para el proximo restarte
